# Generated by Django 3.2.4 on 2021-07-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutpage',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_title', models.CharField(default='We Care,We Excel', help_text='About Page Title', max_length=256)),
                ('about_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'aboutpage',
            },
        ),
    ]
