# Generated by Django 3.2.4 on 2021-07-15 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Blog Title Info', max_length=256, null=True)),
                ('slug', models.SlugField(blank=True, max_length=256, null=True)),
                ('author', models.EmailField(blank=True, help_text='Author is email address holder', max_length=120, null=True)),
                ('updated_on', models.DateTimeField(blank=True, help_text='Blog post modified Time', null=True)),
                ('content', models.TextField(blank=True, help_text='Blog Content', null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Blog post created time', null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('postImage', models.ImageField(blank=True, null=True, upload_to='blog-image/%Y/%m/%d/', verbose_name='Post-related-image')),
            ],
            options={
                'verbose_name': 'BlogPost',
                'verbose_name_plural': 'BlogPost',
                'db_table': 'blogpost',
                'ordering': ['-created_on'],
            },
        ),
    ]
