# Generated by Django 3.2.4 on 2021-07-15 04:51

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(help_text="contact's name", max_length=64)),
                ('contact_time', models.DateTimeField()),
                ('contact_mail', models.EmailField(help_text="contact's email address", max_length=120)),
                ('contact_phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('contact_msg', models.TextField(help_text="contact's message")),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'ContactUs',
                'db_table': 'contact',
                'ordering': ['-contact_time'],
            },
        ),
    ]
