# Generated by Django 3.2.4 on 2021-07-17 06:07

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarecompany',
            name='company_phone',
            field=phone_field.models.PhoneField(help_text='company-official-phone-number', max_length=31),
        ),
    ]
