# Generated by Django 3.2.4 on 2021-07-15 11:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_name', models.CharField(help_text="participant's name", max_length=64)),
                ('participant_time', models.DateTimeField(help_text='Local BanglDesh Time')),
                ('participant_mail', models.EmailField(help_text="participant's email address", max_length=120)),
                ('participant_phone', phone_field.models.PhoneField(help_text="participant's phone number", max_length=31)),
                ('participant_linkedIn', models.URLField(blank=True, help_text="participant's Linkedin Profile Link", null=True, verbose_name='LinkidIn-Id')),
                ('participant_github', models.URLField(blank=True, help_text="participant's Github Profile Link", null=True, verbose_name='Github-Id')),
                ('participant_msg', models.TextField(help_text="participant's msg to get job")),
                ('participant_resume', models.FileField(blank=True, null=True, upload_to='resume/%Y/%m/%d/', verbose_name='Resume')),
                ('participant_cover_letter', models.FileField(blank=True, null=True, upload_to='cover-letter/%Y/%m/%d/', verbose_name='Cover-Letter')),
            ],
            options={
                'verbose_name': 'JobRequest',
                'verbose_name_plural': 'JobRequest',
                'db_table': 'jobrequest',
                'ordering': ['-participant_time'],
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_time',
            field=models.DateTimeField(help_text='Local BanglDesh Time'),
        ),
    ]
