# Generated by Django 3.2.4 on 2021-07-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0002_alter_softwarecompany_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarecompany',
            name='company_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='company-facebook-link-(if any)'),
        ),
        migrations.AddField(
            model_name='softwarecompany',
            name='company_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='company-instagram-link-(if any)'),
        ),
        migrations.AddField(
            model_name='softwarecompany',
            name='company_linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='company-linkedin-link-(if any)'),
        ),
        migrations.AddField(
            model_name='softwarecompany',
            name='company_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='company-youtube-link-(if any)'),
        ),
    ]
