# Generated by Django 3.2.4 on 2021-07-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0003_auto_20210717_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourclients',
            name='client_quote',
            field=models.TextField(blank=True, help_text="Client's quote for us", null=True, verbose_name="Client's comment"),
        ),
        migrations.AlterField(
            model_name='commentbox',
            name='comment_body',
            field=models.TextField(verbose_name='your thought'),
        ),
        migrations.AlterField(
            model_name='commentbox',
            name='commentator_email',
            field=models.EmailField(max_length=120, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='commentbox',
            name='commentator_name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
    ]
