# Generated by Django 3.2.4 on 2021-07-16 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0003_alter_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_name', models.CharField(help_text="Commentator's name", max_length=120)),
                ('commentator_email', models.EmailField(help_text="Commentator's email address", max_length=120)),
                ('comment_body', models.TextField(help_text='Comments Content')),
                ('comment_posted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Comment created time', null=True)),
                ('comment_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('commented_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aztech.blogpost')),
            ],
            options={
                'verbose_name': 'CommentBox',
                'verbose_name_plural': 'CommentBox',
                'db_table': 'commentbox',
                'ordering': ['-comment_posted_at'],
            },
        ),
    ]
