# Generated by Django 3.2.4 on 2021-07-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0004_commentbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'in Draft'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='commentbox',
            name='comment_status',
            field=models.IntegerField(choices=[(0, 'in Draft'), (1, 'Published')], default=0),
        ),
    ]
