# Generated by Django 3.2.4 on 2021-07-16 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0005_auto_20210716_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_preview', models.ImageField(blank=True, null=True, upload_to='project_preview/%Y/%m/', verbose_name='Project-slider-related-image(preview)')),
                ('project_title', models.CharField(blank=True, help_text='Project Title', max_length=256, null=True)),
                ('project_client', models.CharField(blank=True, help_text="Project's client descriptions", max_length=256, null=True)),
                ('project_industries', models.CharField(blank=True, help_text='Helpful to which which industries', max_length=256, null=True)),
                ('project_services', models.CharField(blank=True, help_text='Services provided during this project', max_length=256, null=True)),
                ('project_technologies', models.CharField(blank=True, help_text='Technologies used in this Project', max_length=256, null=True)),
                ('project_challenges', models.TextField(blank=True, help_text='Challenges faced to complete this project & the scope of this project', null=True)),
                ('project_solution', models.TextField(blank=True, help_text='Broad description of what solution brings this project', null=True)),
                ('project_solution_pic', models.ImageField(blank=True, null=True, upload_to='project_solutions/%Y/%m/', verbose_name='Project-solution-related-image')),
                ('project_impact', models.TextField(blank=True, help_text='Broad description of what impact brings this project', null=True)),
                ('project_impact_pic', models.ImageField(blank=True, null=True, upload_to='project_impacts/%Y/%m/', verbose_name='Project-impact-related-image')),
                ('project_uploaded_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Project handover/uploaded time', null=True, verbose_name='Project uploaded time')),
                ('project_slug', models.SlugField(blank=True, max_length=256, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'LatestProject',
                'verbose_name_plural': 'LatestProjects',
                'db_table': 'latestprojects',
                'ordering': ['-project_uploaded_time'],
            },
        ),
    ]
